version: '2.3'
services:
  ps0:
    image: tensorflow/tensorflow:1.7.0-gpu
    runtime: nvidia
    restart: on-failure
    container_name: tf-ps0
    volumes:
      - .:/mnist
      - /etc/localtime:/etc/localtime:ro
    working_dir: /mnist
    environment:
      - CUDA_VISIBLE_DEVICES=
    command: 
      - "python" 
      - "src/distributed.py"
      - "--job_name=ps"
      - "--task_index=0" 
      - "--ps_hosts=tf-ps0:2222"
      - "--worker_hosts=tf-worker0:2222,tf-worker1:2222"

  worker0:
    image: tensorflow/tensorflow:1.7.0-gpu
    runtime: nvidia
    restart: on-failure
    container_name: tf-worker0
    volumes:
      - .:/mnist
      - /etc/localtime:/etc/localtime:ro
    working_dir: /mnist
    environment:
      - CUDA_VISIBLE_DEVICES=0
    command: 
      - "python" 
      - "src/distributed.py"
      - "--job_name=worker"
      - "--task_index=0" 
      - "--ps_hosts=tf-ps0:2222"
      - "--worker_hosts=tf-worker0:2222,tf-worker1:2222"

  worker1:
    image: tensorflow/tensorflow:1.7.0-gpu
    restart: on-failure
    runtime: nvidia
    container_name: tf-worker1
    volumes:
      - .:/mnist
      - /etc/localtime:/etc/localtime:ro
    working_dir: /mnist
    environment:
      - CUDA_VISIBLE_DEVICES=1
    command:
      - "python" 
      - "src/distributed.py"
      - "--job_name=worker"
      - "--task_index=1" 
      - "--ps_hosts=tf-ps0:2222"
      - "--worker_hosts=tf-worker0:2222,tf-worker1:2222"
